export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const REGISTER_PAGE_UNLOAD = 'REGISTER_PAGE_UNLOADED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const LOGOUT = 'LOGOUT';

export const APP_LOAD = 'APP_LOAD';

export const SESSION_LOGIN = 'SESSION_LOGIN';
export const SESSION_LOGIN_SUCCESS = 'SESSION_LOGIN_SUCCESS';
export const SESSION_LOGIN_FAILURE = 'SESSION_LOGIN_FAILURE';

export const HOME_PAGE_LOADING = 'HOME_PAGE_LOADING';
export const HOME_PAGE_LOAD_SUCCEEDED = 'HOME_PAGE_LOAD_SUCCEEDED';
export const HOME_PAGE_LOAD_FAILED = 'HOME_PAGE_LOAD_FAILED';
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED';

export const TAB_CHANGING = 'TAB_CHANGING';
export const TAB_CHANGE_SUCCEEDED = 'TAB_CHANGE_SUCCEEDED';
export const TAB_CHANGE_FAILED = 'TAB_CHANGE_FAILED';

export const RESET_ARTICLE_LIST = 'RESET_ARTICLE_LIST';

export const SET_PAGE = 'SET_PAGE';
export const SET_PAGE_SUCCEEDED = 'SET_PAGE_SUCCEEDED';
export const SET_PAGE_FAILED = 'SET_PAGE_FAILED';

export const TAG_FILTERING = 'TAG_FILTERING';
export const TAG_FILTER_SUCCEEDED = 'TAG_FILTER_SUCCEEDED';
export const TAG_FILTER_FAILED = 'TAG_FILTER_FAILED';

export const RESET_REDIRECT = 'RESET_REDIRECT';
export const REDIRECT_TO = 'REDIRECT_TO';

export const FAVORITE_REQUEST = 'FAVORITE_REQUEST';
export const FAVORITE_SUCCESS = 'FAVORITE_SUCCESS';
export const FAVORITE_FAILURE = 'FAVORITE_FAILURE';

export const UNFAVORITE_REQUEST = 'UNFAVORITE_REQUEST';
export const UNFAVORITE_SUCCESS = 'UNFAVORITE_SUCCESS';
export const UNFAVORITE_FAILURE = 'UNFAVORITE_FAILURE';

export const FAVORITE_ARTICLE_REQUEST = 'FAVORITE_ARTICLE_REQUEST';
export const FAVORITE_ARTICLE_SUCCESS = 'FAVORITE_ARTICLE_SUCCESS';
export const FAVORITE_ARTICLE_FAILURE = 'FAVORITE_ARTICLE_FAILURE';

export const UNFAVORITE_ARTICLE_REQUEST = 'UNFAVORITE_ARTICLE_REQUEST';
export const UNFAVORITE_ARTICLE_SUCCESS = 'UNFAVORITE_ARTICLE_SUCCESS';
export const UNFAVORITE_ARTICLE_FAILURE = 'UNFAVORITE_ARTICLE_FAILURE';

export const FOLLOW_REQUEST = 'FOLLOW_REQUEST';
export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS';
export const FOLLOW_FAILURE = 'FOLLOW_FAILURE';

export const UNFOLLOW_REQUEST = 'UNFOLLOW_REQUEST';
export const UNFOLLOW_SUCCESS = 'UNFOLLOW_SUCCESS';
export const UNFOLLOW_FAILURE = 'UNFOLLOW_FAILURE';

export const FOLLOW_PROFILE_REQUEST = 'FOLLOW_PROFILE_REQUEST';
export const FOLLOW_PROFILE_SUCCESS = 'FOLLOW_PROFILE_SUCCESS';
export const FOLLOW_PROFILE_FAILURE = 'FOLLOW_PROFILE_FAILURE';

export const UNFOLLOW_PROFILE_REQUEST = 'UNFOLLOW_PROFILE_REQUEST';
export const UNFOLLOW_PROFILE_SUCCESS = 'UNFOLLOW_PROFILE_SUCCESS';
export const UNFOLLOW_PROFILE_FAILURE = 'UNFOLLOW_PROFILE_FAILURE';

export const ARTICLE_PAGE_LOADING = 'ARTICLE_PAGE_LOADING';
export const ARTICLE_PAGE_LOAD_SUCCEEDED = 'ARTICLE_PAGE_LOAD_SUCCEEDED';
export const ARTICLE_PAGE_LOAD_FAILED = 'ARTICLE_PAGE_LOAD_FAILED';
export const ARTICLE_PAGE_UNLOADED = 'ARTICLE_PAGE_UNLOADED';

export const DELETE_ARTICLE_REQUEST = 'DELETE_ARTICLE_REQUEST';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_FAILURE = 'DELETE_ARTICLE_FAILURE';

export const CREATE_ARTICLE_REQUEST = 'CREATE_ARTICLE_REQUEST';
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_FAILURE = 'CREATE_ARTICLE_FAILURE';

export const UPDATE_ARTICLE_REQUEST = 'UPDATE_ARTICLE_REQUEST';
export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS';
export const UPDATE_ARTICLE_FAILURE = 'UPDATE_ARTICLE_FAILURE';

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE';

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';

export const EDITOR_PAGE_LOADING = 'EDITOR_PAGE_LOADING';
export const EDITOR_PAGE_LOAD_SUCCEEDED = 'EDITOR_PAGE_LOAD_SUCCEEDED';
export const EDITOR_PAGE_LOAD_FAILED = 'EDITOR_PAGE_LOAD_FAILED';
export const EDITOR_PAGE_UNLOADED = 'EDITOR_PAGE_UNLOADED';

export const SETTINGS_PAGE_LOADED = 'SETTINGS_PAGE_LOADED';
export const SETTINGS_PAGE_UNLOADED = 'SETTINGS_PAGE_UNLOADED';

export const PROFILE_PAGE_LOADING = 'PROFILE_PAGE_LOADING';
export const PROFILE_PAGE_LOAD_SUCCEEDED = 'PROFILE_PAGE_LOAD_SUCCEEDED';
export const PROFILE_PAGE_LOAD_FAILED = 'PROFILE_PAGE_LOAD_FAILED';
export const PROFILE_PAGE_UNLOADED = 'PROFILE_PAGE_UNLOADED';

export const CHANGE_TAB_PROFILE = 'CHANGE_TAB_PROFILE';
export const AUTHOR_ARTICLE_LOADING = 'AUTHOR_ARTICLE_LOADING';
export const AUTHOR_ARTICLE_LOAD_SUCCEEDED = 'AUTHOR_ARTICLE_LOAD_SUCCEEDED';
export const AUTHOR_ARTICLE_LOAD_FAILED = 'AUTHOR_ARTICLE_LOAD_FAILED';
